name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.3
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.2
  firebase_messaging_web: ^2.0.2
  flutter_local_notifications: ^6.0.0
  flutter_progress_hud: ^2.0.0
  flutter_secure_storage: ^4.2.0
  google_sign_in: ^5.0.4
  modal_progress_hud: ^0.1.3
  move_to_background: ^1.0.2
  provider: ^4.3.3
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
